name: 测试推送

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_dispatch:
  
# 仅允许管理员手动执行
permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write
  
jobs:
  sendMsg:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库
        uses: actions/checkout@v3
      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: 获取推送信息
        id: getDataPushMsg
        run: |
          echo "user_email$(=git log -n 1 --pretty=format:%ae)" >> $GITHUB_OUTPUT
          echo "user_name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
          echo "commit_msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
      - name: WeChat Work notification by markdown
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "镜像制品打包完成^~^ \n > 仓库: [${{ github.repository }}](${{ github.event.repository.url }}) \n > 制品: []() \n > 提交记录: [commit](${{ github.event.repository.html_url }}/commit/${{ github.sha }}) \n > 提交者: ${{ steps.getDataPushMsg.outputs.user_name }} \n > 提交者Email: ${{ steps.getDataPushMsg.outputs.user_email }} \n > 更新内容: ${{ steps.getDataPushMsg.outputs.commit_msg }} \n"
